# Generated by Django 6.0.7 on 2026-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Royal Trivandrum', max_length=100)),
                ('tagline', models.CharField(default='Your Trusted Real Estate Partner in Trivandrum', max_length=200)),
                ('description', models.TextField(default='Your trusted real estate partner in Trivandrum. Premium properties across Kerala.')),
                ('contact_address', models.CharField(default='TC 24/1256, MG Road, Statue Junction, Thiruvananthapuram, Kerala - 695001', max_length=255)),
                ('contact_phone', models.CharField(default='+91 471 234 5678', max_length=20)),
                ('contact_email', models.EmailField(default='info@royaltrivandrum.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
