# Generated by Django 6.0.7 on 2024-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_content',
            field=models.TextField(default='To provide exceptional real estate services with integrity, transparency, and professionalism. We strive to make the property buying and selling process seamless and rewarding for our clients.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_mission_title',
            field=models.CharField(default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_content',
            field=models.TextField(default='Premium Real Estate has been at the forefront of the real estate industry, delivering exceptional properties and unmatched service to our clients. Founded in 2010, we have grown from a small local agency to one of the most trusted real estate companies in the region.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_title',
            field=models.CharField(default='Our Story', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision_content',
            field=models.TextField(default='To be the most trusted and innovative real estate company, setting new standards in property services and creating lasting value for our clients and communities.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision_title',
            field=models.CharField(default='Our Vision', max_length=200),
        ),
    ]